=== BorisTheBrave/DeBroglie/samples/mxgmn/schema.json
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "definitions": {
        "point": {
            "type": "object",
            "properties": {
                "x": {"type":"number"},
                "y": {"type":"number"},
                "z": {"type":"number"}
            }
        },
        "tile": {"oneOf": [
            {"type": "number"},
            {"type": "string"}
        ]},
        
        "tileArray": {"type": "array", "items": {"$ref": "#/definitions/tile"}}
    },
    "properties": {
        "src": {"type": "string"},
        "dest": {"type": "string"},
        "periodicInput": {"type": "boolean"},
        "periodicInputX": {"type": "boolean"},
        "periodicInputY": {"type": "boolean"},
        "periodicInputZ": {"type": "boolean"},
        "periodic": {"type": "boolean"},
        "periodicX": {"type": "boolean"},
        "periodicY": {"type": "boolean"},
        "periodicZ": {"type": "boolean"},
        "width": {"type": "integer"},
        "height": {"type": "integer"},
        "depth": {"type": "integer"},
        "ground":  {"$ref": "#/definitions/tile"},
        "symmetry":  {"type": "integer"},
        "rotationalSymmetry":  {"type": "integer"},
        "reflectionalSymmetry":  {"type": "boolean"},
        "rotationTreatment": {"type": "string", "enum": ["missing", "unchanged", "generated"]},
        "backtrack": {"type": "boolean"},
        "animate": {"type": "boolean"},
        "model": {
            "oneOf": [
                {
                    "type":"object",
                    "properties": {
                        "type": {"type": "string", "enum": ["overlapping"]},
                        "n": {"type": "integer"}
                    },
                    "required": [
                        "type"
                    ]
                },
                {
                    "type":"object",
                    "properties": {
                        "type": {"type": "string", "enum": ["adjacent"]}
                    },
                    "required": [
                        "type"
                    ]
                }
            ]
        },
        "tiles": {
            "type": "array",
            "items": {
                "type": "object"
            }
        },
        "adjacencies": {
            "type": "array",
            "items": {
                "oneOf": [
                    {
                        "type": "object",
                        "properties": {
                            "left": {"$ref": "#/definitions/tileArray"},
                            "right": {"$ref": "#/definitions/tileArray"}
                        },
                        "required": [
                            "left",
                            "right"
                        ]
                    },
                    {
                        "type": "object",
                        "properties": {
                            "up": {"$ref": "#/definitions/tileArray"},
                            "down": {"$ref": "#/definitions/tileArray"}
                        },
                        "required": [
                            "up",
                            "down"
                        ]
                    },
                    {
                        "type": "object",
                        "properties": {
                            "above": {"$ref": "#/definitions/tileArray"},
                            "below": {"$ref": "#/definitions/tileArray"}
                        },
                        "required": [
                            "above",
                            "below"
                        ]
                    }
                ]
            }
        },
        "constraints": {
            "type": "array",
            "items": {
                "oneOf": [
                    {
                        "type":"object",
                        "properties": {
                            "type": {"type": "string", "enum": ["path", "edgedPath"]},
                            "tile": {"$ref": "#/definitions/tile"},
                            "tiles": {"$ref": "#/definitions/tileArray"},
                            "endPoints": {"type": "array", "items": {"$ref": "#/definitions/point"}}
                        },
                        "required": [
                            "type"
                        ]
                    },
                    {
                        "type":"object",
                        "properties": {
                            "type": {"type": "string", "enum": ["border"]},
                            "tile": {"$ref": "#/definitions/tile"},
                            "tiles": {"$ref": "#/definitions/tileArray"},
                            "sides": {"type": "string"},
                            "excludeSides": {"type": "string"},
                            "invertArea": {"type": "boolean"},
                            "ban": {"type": "boolean"}
                        },
                        "required": [
                            "type"
                        ]
                    },
                    {
                        "type":"object",
                        "properties": {
                            "type": {"type": "string", "enum": ["fixedTile"]},
                            "tile": {"$ref": "#/definitions/tile"},
                            "tiles": {"$ref": "#/definitions/tileArray"},
                            "point": {"$ref": "#/definitions/point"}
                        },
                        "required": [
                            "type"
                        ]
                    },
                    {
                        "type":"object",
                        "properties": {
                            "type": {"type": "string", "enum": ["maxConsecutive"]},
                            "tile": {"$ref": "#/definitions/tile"},
                            "tiles": {"$ref": "#/definitions/tileArray"},
                            "maxCount": { "type": "number" },
                            "axes": {"type": "array", "items": {"type": "string"}}
                        },
                        "required": [
                            "type"
                        ]
                    },
                    {
                        "type":"object",
                        "properties": {
                            "type": {"type": "string", "enum": ["mirror"]}
                        },
                        "required": [
                            "type"
                        ]
                    }
                ]
            }
        }
    },
    "required": [
        "dest"
    ]
}

=== BorisTheBrave/DeBroglie/samples/grass/map.json
{
    "$schema": "./schema.json",
    "src": "map.tmx",
    "dest": "output/output.tmx",
    "symmetry": 8,
    "model": {
        "type": "adjacent"
    },
    "tiles": [
        {"value": 1, "rotateCw": 1, "reflectX": 1, "changeFrequency": -0.9},
        {"value": 6, "rotateCw": 17, "reflectX": 8, "changeFrequency": -0.9},
        {"value": 8, "rotateCw": 41, "reflectX": 6, "changeFrequency": -0.9},
        {"value": 17, "rotateCw": 8, "reflectX": 17, "changeFrequency": -0.9},
        {"value": 41, "rotateCw": 6, "reflectX": 41, "changeFrequency": -0.9},
        {"value": 18, "rotateCw": 20, "reflectX": 20},
        {"value": 20, "rotateCw": 44, "reflectX": 18},
        {"value": 44, "rotateCw": 42, "reflectX": 42},
        {"value": 42, "rotateCw": 18, "reflectX": 44},
        {"value": 7, "rotateCw": 29, "reflectX": 7},
        {"value": 29, "rotateCw": 7, "reflectX": 29},
        {"value": 30, "rotateCw": 19, "reflectX": 32},
        {"value": 19, "rotateCw": 32, "reflectX": 19},
        {"value": 32, "rotateCw": 43, "reflectX": 30},
        {"value": 43, "rotateCw": 30, "reflectX": 43}
    ],
    "constraints": [
        {
            "type": "path",
            "pathTiles": [6,7,8,17,18,19,20,29,30,31,32,41,42,43,44]
        },
        {
            "type": "border",
            "tile": 1
        }
    ],
    "width": 20,
    "height": 20,
    "periodic": false,
    "backtrack": true,
    "animate": true
}
